// Copyright (c) Daniel Crenna & Contributors. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System.Runtime.InteropServices;
using System.Text;

namespace Blowdart.UI.Tests;

internal static class StringBuilderExtensions
{
	public static void AppendAutoGeneratedHeader(this StringBuilder sb)
	{
		sb.AppendLine("//------------------------------------------------------------------------------");
		sb.AppendLine("// <auto-generated>");
		sb.AppendLine("//     This code was generated by a tool.");
		sb.AppendLine($"//     Runtime Version: {RuntimeInformation.FrameworkDescription}");
		sb.AppendLine("//");
		sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
		sb.AppendLine("//     the code is regenerated.");
		sb.AppendLine("// </auto-generated>");
		sb.AppendLine("//------------------------------------------------------------------------------");
		sb.AppendLine();
	}
}