//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: .NET Core 3.1.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace

public static class HtmlTags
{

    public const string A = "a";
    public const string Abbr = "abbr";
    public const string Address = "address";
    public const string Area = "area";
    public const string Article = "article";
    public const string Aside = "aside";
    public const string Audio = "audio";
    public const string B = "b";
    public const string Base = "base";
    public const string Bdi = "bdi";
    public const string Bdo = "bdo";
    public const string Blockquote = "blockquote";
    public const string Body = "body";
    public const string Br = "br";
    public const string Button = "button";
    public const string Canvas = "canvas";
    public const string Cite = "cite";
    public const string Code = "code";
    public const string Col = "col";
    public const string Colgroup = "colgroup";
    public const string Data = "data";
    public const string Datalist = "datalist";
    public const string Dd = "dd";
    public const string Del = "del";
    public const string Details = "details";
    public const string Dfn = "dfn";
    public const string Dialog = "dialog";
    public const string Div = "div";
    public const string Dl = "dl";
    public const string Dt = "dt";
    public const string Em = "em";
    public const string Embed = "embed";
    public const string Fieldset = "fieldset";
    public const string Figcaption = "figcaption";
    public const string Figure = "figure";
    public const string Footer = "footer";
    public const string Form = "form";
    public const string H1 = "h1";
    public const string H2 = "h2";
    public const string H3 = "h3";
    public const string H4 = "h4";
    public const string H5 = "h5";
    public const string H6 = "h6";
    public const string Head = "head";
    public const string Header = "header";
    public const string Hr = "hr";
    public const string Html = "html";
    public const string I = "i";
    public const string Iframe = "iframe";
    public const string Img = "img";
    public const string Input = "input";
    public const string Ins = "ins";
    public const string Kbd = "kbd";
    public const string Label = "label";
    public const string Legend = "legend";
    public const string Li = "li";
    public const string Link = "link";
    public const string Main = "main";
    public const string Map = "map";
    public const string Mark = "mark";
    public const string Meta = "meta";
    public const string Meter = "meter";
    public const string Nav = "nav";
    public const string Noscript = "noscript";
    public const string Object = "object";
    public const string Ol = "ol";
    public const string Optgroup = "optgroup";
    public const string Option = "option";
    public const string Output = "output";
    public const string P = "p";
    public const string Param = "param";
    public const string Picture = "picture";
    public const string Pre = "pre";
    public const string Progress = "progress";
    public const string Q = "q";
    public const string Rp = "rp";
    public const string Rt = "rt";
    public const string Ruby = "ruby";
    public const string S = "s";
    public const string Samp = "samp";
    public const string Script = "script";
    public const string Section = "section";
    public const string Select = "select";
    public const string Small = "small";
    public const string Source = "source";
    public const string Span = "span";
    public const string Strong = "strong";
    public const string Style = "style";
    public const string Sub = "sub";
    public const string Summary = "summary";
    public const string Sup = "sup";
    public const string Svg = "svg";
    public const string Table = "table";
    public const string Tbody = "tbody";
    public const string Td = "td";
    public const string Template = "template";
    public const string Textarea = "textarea";
    public const string Tfoot = "tfoot";
    public const string Th = "th";
    public const string Thead = "thead";
    public const string Time = "time";
    public const string Title = "title";
    public const string Tr = "tr";
    public const string Track = "track";
    public const string U = "u";
    public const string Ul = "ul";
    public const string Var = "var";
    public const string Video = "video";
    public const string Wbr = "wbr";
}