//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: .NET Core 3.1.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace

public static class HtmlAttributes
{
    public const string Class = "class";
    public const string Accept = "accept";
    public const string Accesskey = "accesskey";
    public const string Action = "action";
    public const string Alt = "alt";
    public const string Async = "async";
    public const string Autocomplete = "autocomplete";
    public const string Contenteditable = "contenteditable";
    public const string Id = "id";
    public const string Role = "role";
}

