//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: .NET 9.0.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;

namespace Blowdart.UI.Blazor
{
    partial class ImGui
    {
        #region Keyboard

        public EventCallback<KeyboardEventArgs> OnKeyDown(UInt128 id, Func<KeyboardEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<KeyboardEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Keyboard.OnKeyDown, args);
            });
        }

        public EventCallback<KeyboardEventArgs> OnKeyPress(UInt128 id, Func<KeyboardEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<KeyboardEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Keyboard.OnKeyPress, args);
            });
        }

        public EventCallback<KeyboardEventArgs> OnKeyUp(UInt128 id, Func<KeyboardEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<KeyboardEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Keyboard.OnKeyUp, args);
            });
        }

        #endregion

        #region Mouse

        public EventCallback<MouseEventArgs> OnClick(UInt128 id, Func<MouseEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<MouseEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Mouse.OnClick, args);
            });
        }

        public EventCallback<MouseEventArgs> OnDoubleClick(UInt128 id, Func<MouseEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<MouseEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Mouse.OnDoubleClick, args);
            });
        }

        public EventCallback<MouseEventArgs> OnMouseDown(UInt128 id, Func<MouseEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<MouseEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Mouse.OnMouseDown, args);
            });
        }

        public EventCallback<MouseEventArgs> OnMouseMove(UInt128 id, Func<MouseEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<MouseEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Mouse.OnMouseMove, args);
            });
        }

        public EventCallback<MouseEventArgs> OnMouseOut(UInt128 id, Func<MouseEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<MouseEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Mouse.OnMouseOut, args);
            });
        }

        public EventCallback<MouseEventArgs> OnMouseOver(UInt128 id, Func<MouseEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<MouseEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Mouse.OnMouseOver, args);
            });
        }

        public EventCallback<MouseEventArgs> OnMouseUp(UInt128 id, Func<MouseEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<MouseEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Mouse.OnMouseUp, args);
            });
        }

        public EventCallback<MouseEventArgs> OnWheel(UInt128 id, Func<MouseEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<MouseEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Mouse.OnWheel, args);
            });
        }

        #endregion

        #region Clipboard

        public EventCallback<ClipboardEventArgs> OnCopy(UInt128 id, Func<ClipboardEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<ClipboardEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Clipboard.OnCopy, args);
            });
        }

        public EventCallback<ClipboardEventArgs> OnCut(UInt128 id, Func<ClipboardEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<ClipboardEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Clipboard.OnCut, args);
            });
        }

        public EventCallback<ClipboardEventArgs> OnPaste(UInt128 id, Func<ClipboardEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<ClipboardEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Clipboard.OnPaste, args);
            });
        }

        #endregion

        #region Drag

        public EventCallback<DragEventArgs> OnDrag(UInt128 id, Func<DragEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<DragEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Drag.OnDrag, args);
            });
        }

        public EventCallback<DragEventArgs> OnDragEnd(UInt128 id, Func<DragEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<DragEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Drag.OnDragEnd, args);
            });
        }

        public EventCallback<DragEventArgs> OnDragEnter(UInt128 id, Func<DragEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<DragEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Drag.OnDragEnter, args);
            });
        }

        public EventCallback<DragEventArgs> OnDragLeave(UInt128 id, Func<DragEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<DragEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Drag.OnDragLeave, args);
            });
        }

        public EventCallback<DragEventArgs> OnDragOver(UInt128 id, Func<DragEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<DragEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Drag.OnDragOver, args);
            });
        }

        public EventCallback<DragEventArgs> OnDragStart(UInt128 id, Func<DragEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<DragEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Drag.OnDragStart, args);
            });
        }

        public EventCallback<DragEventArgs> OnDrop(UInt128 id, Func<DragEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<DragEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Drag.OnDrop, args);
            });
        }

        public EventCallback<DragEventArgs> OnScroll(UInt128 id, Func<DragEventArgs, bool>? predicate = null)
        {
            return EventCallback.Factory.Create<DragEventArgs>(this, args =>
            {
                OnEvent(id, HtmlEvents.Drag.OnScroll, args);
            });
        }

        #endregion

    }
}

