//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: .NET 5.0.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Components.Rendering;

// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global

namespace Blowdart.UI.Blazor
{
    [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "HTML elements")]
    public static partial class RenderTreeBuilderExtensions
    {
        public static RenderTreeBuilder BeginA(this RenderTreeBuilder b) => b.ElementOpen("a");
        public static RenderTreeBuilder EndA(this RenderTreeBuilder b) => b.ElementClose("a");

        public static RenderTreeBuilder BeginAbbr(this RenderTreeBuilder b) => b.ElementOpen("abbr");
        public static RenderTreeBuilder EndAbbr(this RenderTreeBuilder b) => b.ElementClose("abbr");

        public static RenderTreeBuilder BeginAddress(this RenderTreeBuilder b) => b.ElementOpen("address");
        public static RenderTreeBuilder EndAddress(this RenderTreeBuilder b) => b.ElementClose("address");

        public static RenderTreeBuilder BeginArea(this RenderTreeBuilder b) => b.ElementOpen("area");
        public static RenderTreeBuilder EndArea(this RenderTreeBuilder b) => b.ElementClose("area");

        public static RenderTreeBuilder BeginArticle(this RenderTreeBuilder b) => b.ElementOpen("article");
        public static RenderTreeBuilder EndArticle(this RenderTreeBuilder b) => b.ElementClose("article");

        public static RenderTreeBuilder BeginAside(this RenderTreeBuilder b) => b.ElementOpen("aside");
        public static RenderTreeBuilder EndAside(this RenderTreeBuilder b) => b.ElementClose("aside");

        public static RenderTreeBuilder BeginAudio(this RenderTreeBuilder b) => b.ElementOpen("audio");
        public static RenderTreeBuilder EndAudio(this RenderTreeBuilder b) => b.ElementClose("audio");

        public static RenderTreeBuilder BeginB(this RenderTreeBuilder b) => b.ElementOpen("b");
        public static RenderTreeBuilder EndB(this RenderTreeBuilder b) => b.ElementClose("b");

        public static RenderTreeBuilder BeginBase(this RenderTreeBuilder b) => b.ElementOpen("base");
        public static RenderTreeBuilder EndBase(this RenderTreeBuilder b) => b.ElementClose("base");

        public static RenderTreeBuilder BeginBdi(this RenderTreeBuilder b) => b.ElementOpen("bdi");
        public static RenderTreeBuilder EndBdi(this RenderTreeBuilder b) => b.ElementClose("bdi");

        public static RenderTreeBuilder BeginBdo(this RenderTreeBuilder b) => b.ElementOpen("bdo");
        public static RenderTreeBuilder EndBdo(this RenderTreeBuilder b) => b.ElementClose("bdo");

        public static RenderTreeBuilder BeginBlockquote(this RenderTreeBuilder b) => b.ElementOpen("blockquote");
        public static RenderTreeBuilder EndBlockquote(this RenderTreeBuilder b) => b.ElementClose("blockquote");

        public static RenderTreeBuilder BeginBody(this RenderTreeBuilder b) => b.ElementOpen("body");
        public static RenderTreeBuilder EndBody(this RenderTreeBuilder b) => b.ElementClose("body");

        public static RenderTreeBuilder BeginBr(this RenderTreeBuilder b) => b.ElementOpen("br");
        public static RenderTreeBuilder EndBr(this RenderTreeBuilder b) => b.ElementClose("br");

        public static RenderTreeBuilder BeginButton(this RenderTreeBuilder b) => b.ElementOpen("button");
        public static RenderTreeBuilder EndButton(this RenderTreeBuilder b) => b.ElementClose("button");

        public static RenderTreeBuilder BeginCanvas(this RenderTreeBuilder b) => b.ElementOpen("canvas");
        public static RenderTreeBuilder EndCanvas(this RenderTreeBuilder b) => b.ElementClose("canvas");

        public static RenderTreeBuilder BeginCite(this RenderTreeBuilder b) => b.ElementOpen("cite");
        public static RenderTreeBuilder EndCite(this RenderTreeBuilder b) => b.ElementClose("cite");

        public static RenderTreeBuilder BeginCode(this RenderTreeBuilder b) => b.ElementOpen("code");
        public static RenderTreeBuilder EndCode(this RenderTreeBuilder b) => b.ElementClose("code");

        public static RenderTreeBuilder BeginCol(this RenderTreeBuilder b) => b.ElementOpen("col");
        public static RenderTreeBuilder EndCol(this RenderTreeBuilder b) => b.ElementClose("col");

        public static RenderTreeBuilder BeginColgroup(this RenderTreeBuilder b) => b.ElementOpen("colgroup");
        public static RenderTreeBuilder EndColgroup(this RenderTreeBuilder b) => b.ElementClose("colgroup");

        public static RenderTreeBuilder BeginData(this RenderTreeBuilder b) => b.ElementOpen("data");
        public static RenderTreeBuilder EndData(this RenderTreeBuilder b) => b.ElementClose("data");

        public static RenderTreeBuilder BeginDatalist(this RenderTreeBuilder b) => b.ElementOpen("datalist");
        public static RenderTreeBuilder EndDatalist(this RenderTreeBuilder b) => b.ElementClose("datalist");

        public static RenderTreeBuilder BeginDd(this RenderTreeBuilder b) => b.ElementOpen("dd");
        public static RenderTreeBuilder EndDd(this RenderTreeBuilder b) => b.ElementClose("dd");

        public static RenderTreeBuilder BeginDel(this RenderTreeBuilder b) => b.ElementOpen("del");
        public static RenderTreeBuilder EndDel(this RenderTreeBuilder b) => b.ElementClose("del");

        public static RenderTreeBuilder BeginDetails(this RenderTreeBuilder b) => b.ElementOpen("details");
        public static RenderTreeBuilder EndDetails(this RenderTreeBuilder b) => b.ElementClose("details");

        public static RenderTreeBuilder BeginDfn(this RenderTreeBuilder b) => b.ElementOpen("dfn");
        public static RenderTreeBuilder EndDfn(this RenderTreeBuilder b) => b.ElementClose("dfn");

        public static RenderTreeBuilder BeginDialog(this RenderTreeBuilder b) => b.ElementOpen("dialog");
        public static RenderTreeBuilder EndDialog(this RenderTreeBuilder b) => b.ElementClose("dialog");

        public static RenderTreeBuilder BeginDiv(this RenderTreeBuilder b) => b.ElementOpen("div");
        public static RenderTreeBuilder EndDiv(this RenderTreeBuilder b) => b.ElementClose("div");

        public static RenderTreeBuilder BeginDl(this RenderTreeBuilder b) => b.ElementOpen("dl");
        public static RenderTreeBuilder EndDl(this RenderTreeBuilder b) => b.ElementClose("dl");

        public static RenderTreeBuilder BeginDt(this RenderTreeBuilder b) => b.ElementOpen("dt");
        public static RenderTreeBuilder EndDt(this RenderTreeBuilder b) => b.ElementClose("dt");

        public static RenderTreeBuilder BeginEm(this RenderTreeBuilder b) => b.ElementOpen("em");
        public static RenderTreeBuilder EndEm(this RenderTreeBuilder b) => b.ElementClose("em");

        public static RenderTreeBuilder BeginEmbed(this RenderTreeBuilder b) => b.ElementOpen("embed");
        public static RenderTreeBuilder EndEmbed(this RenderTreeBuilder b) => b.ElementClose("embed");

        public static RenderTreeBuilder BeginFieldset(this RenderTreeBuilder b) => b.ElementOpen("fieldset");
        public static RenderTreeBuilder EndFieldset(this RenderTreeBuilder b) => b.ElementClose("fieldset");

        public static RenderTreeBuilder BeginFigcaption(this RenderTreeBuilder b) => b.ElementOpen("figcaption");
        public static RenderTreeBuilder EndFigcaption(this RenderTreeBuilder b) => b.ElementClose("figcaption");

        public static RenderTreeBuilder BeginFigure(this RenderTreeBuilder b) => b.ElementOpen("figure");
        public static RenderTreeBuilder EndFigure(this RenderTreeBuilder b) => b.ElementClose("figure");

        public static RenderTreeBuilder BeginFooter(this RenderTreeBuilder b) => b.ElementOpen("footer");
        public static RenderTreeBuilder EndFooter(this RenderTreeBuilder b) => b.ElementClose("footer");

        public static RenderTreeBuilder BeginForm(this RenderTreeBuilder b) => b.ElementOpen("form");
        public static RenderTreeBuilder EndForm(this RenderTreeBuilder b) => b.ElementClose("form");

        public static RenderTreeBuilder BeginH1(this RenderTreeBuilder b) => b.ElementOpen("h1");
        public static RenderTreeBuilder EndH1(this RenderTreeBuilder b) => b.ElementClose("h1");

        public static RenderTreeBuilder BeginH2(this RenderTreeBuilder b) => b.ElementOpen("h2");
        public static RenderTreeBuilder EndH2(this RenderTreeBuilder b) => b.ElementClose("h2");

        public static RenderTreeBuilder BeginH3(this RenderTreeBuilder b) => b.ElementOpen("h3");
        public static RenderTreeBuilder EndH3(this RenderTreeBuilder b) => b.ElementClose("h3");

        public static RenderTreeBuilder BeginH4(this RenderTreeBuilder b) => b.ElementOpen("h4");
        public static RenderTreeBuilder EndH4(this RenderTreeBuilder b) => b.ElementClose("h4");

        public static RenderTreeBuilder BeginH5(this RenderTreeBuilder b) => b.ElementOpen("h5");
        public static RenderTreeBuilder EndH5(this RenderTreeBuilder b) => b.ElementClose("h5");

        public static RenderTreeBuilder BeginH6(this RenderTreeBuilder b) => b.ElementOpen("h6");
        public static RenderTreeBuilder EndH6(this RenderTreeBuilder b) => b.ElementClose("h6");

        public static RenderTreeBuilder BeginHead(this RenderTreeBuilder b) => b.ElementOpen("head");
        public static RenderTreeBuilder EndHead(this RenderTreeBuilder b) => b.ElementClose("head");

        public static RenderTreeBuilder BeginHeader(this RenderTreeBuilder b) => b.ElementOpen("header");
        public static RenderTreeBuilder EndHeader(this RenderTreeBuilder b) => b.ElementClose("header");

        public static RenderTreeBuilder BeginHr(this RenderTreeBuilder b) => b.ElementOpen("hr");
        public static RenderTreeBuilder EndHr(this RenderTreeBuilder b) => b.ElementClose("hr");

        public static RenderTreeBuilder BeginHtml(this RenderTreeBuilder b) => b.ElementOpen("html");
        public static RenderTreeBuilder EndHtml(this RenderTreeBuilder b) => b.ElementClose("html");

        public static RenderTreeBuilder BeginI(this RenderTreeBuilder b) => b.ElementOpen("i");
        public static RenderTreeBuilder EndI(this RenderTreeBuilder b) => b.ElementClose("i");

        public static RenderTreeBuilder BeginIframe(this RenderTreeBuilder b) => b.ElementOpen("iframe");
        public static RenderTreeBuilder EndIframe(this RenderTreeBuilder b) => b.ElementClose("iframe");

        public static RenderTreeBuilder BeginImg(this RenderTreeBuilder b) => b.ElementOpen("img");
        public static RenderTreeBuilder EndImg(this RenderTreeBuilder b) => b.ElementClose("img");

        public static RenderTreeBuilder BeginInput(this RenderTreeBuilder b) => b.ElementOpen("input");
        public static RenderTreeBuilder EndInput(this RenderTreeBuilder b) => b.ElementClose("input");

        public static RenderTreeBuilder BeginIns(this RenderTreeBuilder b) => b.ElementOpen("ins");
        public static RenderTreeBuilder EndIns(this RenderTreeBuilder b) => b.ElementClose("ins");

        public static RenderTreeBuilder BeginKbd(this RenderTreeBuilder b) => b.ElementOpen("kbd");
        public static RenderTreeBuilder EndKbd(this RenderTreeBuilder b) => b.ElementClose("kbd");

        public static RenderTreeBuilder BeginLabel(this RenderTreeBuilder b) => b.ElementOpen("label");
        public static RenderTreeBuilder EndLabel(this RenderTreeBuilder b) => b.ElementClose("label");

        public static RenderTreeBuilder BeginLegend(this RenderTreeBuilder b) => b.ElementOpen("legend");
        public static RenderTreeBuilder EndLegend(this RenderTreeBuilder b) => b.ElementClose("legend");

        public static RenderTreeBuilder BeginLi(this RenderTreeBuilder b) => b.ElementOpen("li");
        public static RenderTreeBuilder EndLi(this RenderTreeBuilder b) => b.ElementClose("li");

        public static RenderTreeBuilder BeginLink(this RenderTreeBuilder b) => b.ElementOpen("link");
        public static RenderTreeBuilder EndLink(this RenderTreeBuilder b) => b.ElementClose("link");

        public static RenderTreeBuilder BeginMain(this RenderTreeBuilder b) => b.ElementOpen("main");
        public static RenderTreeBuilder EndMain(this RenderTreeBuilder b) => b.ElementClose("main");

        public static RenderTreeBuilder BeginMap(this RenderTreeBuilder b) => b.ElementOpen("map");
        public static RenderTreeBuilder EndMap(this RenderTreeBuilder b) => b.ElementClose("map");

        public static RenderTreeBuilder BeginMark(this RenderTreeBuilder b) => b.ElementOpen("mark");
        public static RenderTreeBuilder EndMark(this RenderTreeBuilder b) => b.ElementClose("mark");

        public static RenderTreeBuilder BeginMeta(this RenderTreeBuilder b) => b.ElementOpen("meta");
        public static RenderTreeBuilder EndMeta(this RenderTreeBuilder b) => b.ElementClose("meta");

        public static RenderTreeBuilder BeginMeter(this RenderTreeBuilder b) => b.ElementOpen("meter");
        public static RenderTreeBuilder EndMeter(this RenderTreeBuilder b) => b.ElementClose("meter");

        public static RenderTreeBuilder BeginNav(this RenderTreeBuilder b) => b.ElementOpen("nav");
        public static RenderTreeBuilder EndNav(this RenderTreeBuilder b) => b.ElementClose("nav");

        public static RenderTreeBuilder BeginNoscript(this RenderTreeBuilder b) => b.ElementOpen("noscript");
        public static RenderTreeBuilder EndNoscript(this RenderTreeBuilder b) => b.ElementClose("noscript");

        public static RenderTreeBuilder BeginObject(this RenderTreeBuilder b) => b.ElementOpen("object");
        public static RenderTreeBuilder EndObject(this RenderTreeBuilder b) => b.ElementClose("object");

        public static RenderTreeBuilder BeginOl(this RenderTreeBuilder b) => b.ElementOpen("ol");
        public static RenderTreeBuilder EndOl(this RenderTreeBuilder b) => b.ElementClose("ol");

        public static RenderTreeBuilder BeginOptgroup(this RenderTreeBuilder b) => b.ElementOpen("optgroup");
        public static RenderTreeBuilder EndOptgroup(this RenderTreeBuilder b) => b.ElementClose("optgroup");

        public static RenderTreeBuilder BeginOption(this RenderTreeBuilder b) => b.ElementOpen("option");
        public static RenderTreeBuilder EndOption(this RenderTreeBuilder b) => b.ElementClose("option");

        public static RenderTreeBuilder BeginOutput(this RenderTreeBuilder b) => b.ElementOpen("output");
        public static RenderTreeBuilder EndOutput(this RenderTreeBuilder b) => b.ElementClose("output");

        public static RenderTreeBuilder BeginP(this RenderTreeBuilder b) => b.ElementOpen("p");
        public static RenderTreeBuilder EndP(this RenderTreeBuilder b) => b.ElementClose("p");

        public static RenderTreeBuilder BeginParam(this RenderTreeBuilder b) => b.ElementOpen("param");
        public static RenderTreeBuilder EndParam(this RenderTreeBuilder b) => b.ElementClose("param");

        public static RenderTreeBuilder BeginPicture(this RenderTreeBuilder b) => b.ElementOpen("picture");
        public static RenderTreeBuilder EndPicture(this RenderTreeBuilder b) => b.ElementClose("picture");

        public static RenderTreeBuilder BeginPre(this RenderTreeBuilder b) => b.ElementOpen("pre");
        public static RenderTreeBuilder EndPre(this RenderTreeBuilder b) => b.ElementClose("pre");

        public static RenderTreeBuilder BeginProgress(this RenderTreeBuilder b) => b.ElementOpen("progress");
        public static RenderTreeBuilder EndProgress(this RenderTreeBuilder b) => b.ElementClose("progress");

        public static RenderTreeBuilder BeginQ(this RenderTreeBuilder b) => b.ElementOpen("q");
        public static RenderTreeBuilder EndQ(this RenderTreeBuilder b) => b.ElementClose("q");

        public static RenderTreeBuilder BeginRp(this RenderTreeBuilder b) => b.ElementOpen("rp");
        public static RenderTreeBuilder EndRp(this RenderTreeBuilder b) => b.ElementClose("rp");

        public static RenderTreeBuilder BeginRt(this RenderTreeBuilder b) => b.ElementOpen("rt");
        public static RenderTreeBuilder EndRt(this RenderTreeBuilder b) => b.ElementClose("rt");

        public static RenderTreeBuilder BeginRuby(this RenderTreeBuilder b) => b.ElementOpen("ruby");
        public static RenderTreeBuilder EndRuby(this RenderTreeBuilder b) => b.ElementClose("ruby");

        public static RenderTreeBuilder BeginS(this RenderTreeBuilder b) => b.ElementOpen("s");
        public static RenderTreeBuilder EndS(this RenderTreeBuilder b) => b.ElementClose("s");

        public static RenderTreeBuilder BeginSamp(this RenderTreeBuilder b) => b.ElementOpen("samp");
        public static RenderTreeBuilder EndSamp(this RenderTreeBuilder b) => b.ElementClose("samp");

        public static RenderTreeBuilder BeginScript(this RenderTreeBuilder b) => b.ElementOpen("script");
        public static RenderTreeBuilder EndScript(this RenderTreeBuilder b) => b.ElementClose("script");

        public static RenderTreeBuilder BeginSection(this RenderTreeBuilder b) => b.ElementOpen("section");
        public static RenderTreeBuilder EndSection(this RenderTreeBuilder b) => b.ElementClose("section");

        public static RenderTreeBuilder BeginSelect(this RenderTreeBuilder b) => b.ElementOpen("select");
        public static RenderTreeBuilder EndSelect(this RenderTreeBuilder b) => b.ElementClose("select");

        public static RenderTreeBuilder BeginSmall(this RenderTreeBuilder b) => b.ElementOpen("small");
        public static RenderTreeBuilder EndSmall(this RenderTreeBuilder b) => b.ElementClose("small");

        public static RenderTreeBuilder BeginSource(this RenderTreeBuilder b) => b.ElementOpen("source");
        public static RenderTreeBuilder EndSource(this RenderTreeBuilder b) => b.ElementClose("source");

        public static RenderTreeBuilder BeginSpan(this RenderTreeBuilder b) => b.ElementOpen("span");
        public static RenderTreeBuilder EndSpan(this RenderTreeBuilder b) => b.ElementClose("span");

        public static RenderTreeBuilder BeginStrong(this RenderTreeBuilder b) => b.ElementOpen("strong");
        public static RenderTreeBuilder EndStrong(this RenderTreeBuilder b) => b.ElementClose("strong");

        public static RenderTreeBuilder BeginStyle(this RenderTreeBuilder b) => b.ElementOpen("style");
        public static RenderTreeBuilder EndStyle(this RenderTreeBuilder b) => b.ElementClose("style");

        public static RenderTreeBuilder BeginSub(this RenderTreeBuilder b) => b.ElementOpen("sub");
        public static RenderTreeBuilder EndSub(this RenderTreeBuilder b) => b.ElementClose("sub");

        public static RenderTreeBuilder BeginSummary(this RenderTreeBuilder b) => b.ElementOpen("summary");
        public static RenderTreeBuilder EndSummary(this RenderTreeBuilder b) => b.ElementClose("summary");

        public static RenderTreeBuilder BeginSup(this RenderTreeBuilder b) => b.ElementOpen("sup");
        public static RenderTreeBuilder EndSup(this RenderTreeBuilder b) => b.ElementClose("sup");

        public static RenderTreeBuilder BeginSvg(this RenderTreeBuilder b) => b.ElementOpen("svg");
        public static RenderTreeBuilder EndSvg(this RenderTreeBuilder b) => b.ElementClose("svg");

        public static RenderTreeBuilder BeginTable(this RenderTreeBuilder b) => b.ElementOpen("table");
        public static RenderTreeBuilder EndTable(this RenderTreeBuilder b) => b.ElementClose("table");

        public static RenderTreeBuilder BeginTbody(this RenderTreeBuilder b) => b.ElementOpen("tbody");
        public static RenderTreeBuilder EndTbody(this RenderTreeBuilder b) => b.ElementClose("tbody");

        public static RenderTreeBuilder BeginTd(this RenderTreeBuilder b) => b.ElementOpen("td");
        public static RenderTreeBuilder EndTd(this RenderTreeBuilder b) => b.ElementClose("td");

        public static RenderTreeBuilder BeginTemplate(this RenderTreeBuilder b) => b.ElementOpen("template");
        public static RenderTreeBuilder EndTemplate(this RenderTreeBuilder b) => b.ElementClose("template");

        public static RenderTreeBuilder BeginTextarea(this RenderTreeBuilder b) => b.ElementOpen("textarea");
        public static RenderTreeBuilder EndTextarea(this RenderTreeBuilder b) => b.ElementClose("textarea");

        public static RenderTreeBuilder BeginTfoot(this RenderTreeBuilder b) => b.ElementOpen("tfoot");
        public static RenderTreeBuilder EndTfoot(this RenderTreeBuilder b) => b.ElementClose("tfoot");

        public static RenderTreeBuilder BeginTh(this RenderTreeBuilder b) => b.ElementOpen("th");
        public static RenderTreeBuilder EndTh(this RenderTreeBuilder b) => b.ElementClose("th");

        public static RenderTreeBuilder BeginThead(this RenderTreeBuilder b) => b.ElementOpen("thead");
        public static RenderTreeBuilder EndThead(this RenderTreeBuilder b) => b.ElementClose("thead");

        public static RenderTreeBuilder BeginTime(this RenderTreeBuilder b) => b.ElementOpen("time");
        public static RenderTreeBuilder EndTime(this RenderTreeBuilder b) => b.ElementClose("time");

        public static RenderTreeBuilder BeginTitle(this RenderTreeBuilder b) => b.ElementOpen("title");
        public static RenderTreeBuilder EndTitle(this RenderTreeBuilder b) => b.ElementClose("title");

        public static RenderTreeBuilder BeginTr(this RenderTreeBuilder b) => b.ElementOpen("tr");
        public static RenderTreeBuilder EndTr(this RenderTreeBuilder b) => b.ElementClose("tr");

        public static RenderTreeBuilder BeginTrack(this RenderTreeBuilder b) => b.ElementOpen("track");
        public static RenderTreeBuilder EndTrack(this RenderTreeBuilder b) => b.ElementClose("track");

        public static RenderTreeBuilder BeginU(this RenderTreeBuilder b) => b.ElementOpen("u");
        public static RenderTreeBuilder EndU(this RenderTreeBuilder b) => b.ElementClose("u");

        public static RenderTreeBuilder BeginUl(this RenderTreeBuilder b) => b.ElementOpen("ul");
        public static RenderTreeBuilder EndUl(this RenderTreeBuilder b) => b.ElementClose("ul");

        public static RenderTreeBuilder BeginVar(this RenderTreeBuilder b) => b.ElementOpen("var");
        public static RenderTreeBuilder EndVar(this RenderTreeBuilder b) => b.ElementClose("var");

        public static RenderTreeBuilder BeginVideo(this RenderTreeBuilder b) => b.ElementOpen("video");
        public static RenderTreeBuilder EndVideo(this RenderTreeBuilder b) => b.ElementClose("video");

        public static RenderTreeBuilder BeginWbr(this RenderTreeBuilder b) => b.ElementOpen("wbr");
        public static RenderTreeBuilder EndWbr(this RenderTreeBuilder b) => b.ElementClose("wbr");

    }
}

