
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: .NET 5.0.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Components.Rendering;

// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global

#nullable enable

namespace Blowdart.UI.Blazor
{
    [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "HTML elements")]
    public static partial class RenderTreeBuilderExtensions
    {
        public static RenderTreeBuilder a(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "a", action);

        public static RenderTreeBuilder abbr(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "abbr", action);

        public static RenderTreeBuilder address(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "address", action);

        public static RenderTreeBuilder area(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "area", action);

        public static RenderTreeBuilder article(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "article", action);

        public static RenderTreeBuilder aside(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "aside", action);

        public static RenderTreeBuilder audio(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "audio", action);

        public static RenderTreeBuilder b(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "b", action);

        public static RenderTreeBuilder @base(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "@base", action);

        public static RenderTreeBuilder bdi(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "bdi", action);

        public static RenderTreeBuilder bdo(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "bdo", action);

        public static RenderTreeBuilder blockquote(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "blockquote", action);

        public static RenderTreeBuilder body(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "body", action);

        public static RenderTreeBuilder br(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "br", action);

        public static RenderTreeBuilder button(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "button", action);

        public static RenderTreeBuilder canvas(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "canvas", action);

        public static RenderTreeBuilder cite(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "cite", action);

        public static RenderTreeBuilder code(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "code", action);

        public static RenderTreeBuilder col(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "col", action);

        public static RenderTreeBuilder colgroup(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "colgroup", action);

        public static RenderTreeBuilder data(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "data", action);

        public static RenderTreeBuilder datalist(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "datalist", action);

        public static RenderTreeBuilder dd(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "dd", action);

        public static RenderTreeBuilder del(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "del", action);

        public static RenderTreeBuilder details(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "details", action);

        public static RenderTreeBuilder dfn(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "dfn", action);

        public static RenderTreeBuilder dialog(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "dialog", action);

        public static RenderTreeBuilder div(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "div", action);

        public static RenderTreeBuilder dl(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "dl", action);

        public static RenderTreeBuilder dt(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "dt", action);

        public static RenderTreeBuilder em(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "em", action);

        public static RenderTreeBuilder embed(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "embed", action);

        public static RenderTreeBuilder fieldset(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "fieldset", action);

        public static RenderTreeBuilder figcaption(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "figcaption", action);

        public static RenderTreeBuilder figure(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "figure", action);

        public static RenderTreeBuilder footer(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "footer", action);

        public static RenderTreeBuilder form(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "form", action);

        public static RenderTreeBuilder h1(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "h1", action);

        public static RenderTreeBuilder h2(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "h2", action);

        public static RenderTreeBuilder h3(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "h3", action);

        public static RenderTreeBuilder h4(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "h4", action);

        public static RenderTreeBuilder h5(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "h5", action);

        public static RenderTreeBuilder h6(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "h6", action);

        public static RenderTreeBuilder head(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "head", action);

        public static RenderTreeBuilder header(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "header", action);

        public static RenderTreeBuilder hr(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "hr", action);

        public static RenderTreeBuilder html(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "html", action);

        public static RenderTreeBuilder i(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "i", action);

        public static RenderTreeBuilder iframe(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "iframe", action);

        public static RenderTreeBuilder img(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "img", action);

        public static RenderTreeBuilder input(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "input", action);

        public static RenderTreeBuilder ins(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "ins", action);

        public static RenderTreeBuilder kbd(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "kbd", action);

        public static RenderTreeBuilder label(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "label", action);

        public static RenderTreeBuilder legend(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "legend", action);

        public static RenderTreeBuilder li(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "li", action);

        public static RenderTreeBuilder link(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "link", action);

        public static RenderTreeBuilder main(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "main", action);

        public static RenderTreeBuilder map(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "map", action);

        public static RenderTreeBuilder mark(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "mark", action);

        public static RenderTreeBuilder meta(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "meta", action);

        public static RenderTreeBuilder meter(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "meter", action);

        public static RenderTreeBuilder nav(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "nav", action);

        public static RenderTreeBuilder noscript(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "noscript", action);

        public static RenderTreeBuilder @object(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "@object", action);

        public static RenderTreeBuilder ol(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "ol", action);

        public static RenderTreeBuilder optgroup(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "optgroup", action);

        public static RenderTreeBuilder option(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "option", action);

        public static RenderTreeBuilder output(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "output", action);

        public static RenderTreeBuilder p(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "p", action);

        public static RenderTreeBuilder param(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "param", action);

        public static RenderTreeBuilder picture(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "picture", action);

        public static RenderTreeBuilder pre(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "pre", action);

        public static RenderTreeBuilder progress(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "progress", action);

        public static RenderTreeBuilder q(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "q", action);

        public static RenderTreeBuilder rp(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "rp", action);

        public static RenderTreeBuilder rt(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "rt", action);

        public static RenderTreeBuilder ruby(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "ruby", action);

        public static RenderTreeBuilder s(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "s", action);

        public static RenderTreeBuilder samp(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "samp", action);

        public static RenderTreeBuilder script(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "script", action);

        public static RenderTreeBuilder section(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "section", action);

        public static RenderTreeBuilder select(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "select", action);

        public static RenderTreeBuilder small(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "small", action);

        public static RenderTreeBuilder source(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "source", action);

        public static RenderTreeBuilder span(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "span", action);

        public static RenderTreeBuilder strong(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "strong", action);

        public static RenderTreeBuilder style(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "style", action);

        public static RenderTreeBuilder sub(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "sub", action);

        public static RenderTreeBuilder summary(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "summary", action);

        public static RenderTreeBuilder sup(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "sup", action);

        public static RenderTreeBuilder svg(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "svg", action);

        public static RenderTreeBuilder table(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "table", action);

        public static RenderTreeBuilder tbody(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "tbody", action);

        public static RenderTreeBuilder td(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "td", action);

        public static RenderTreeBuilder template(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "template", action);

        public static RenderTreeBuilder textarea(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "textarea", action);

        public static RenderTreeBuilder tfoot(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "tfoot", action);

        public static RenderTreeBuilder th(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "th", action);

        public static RenderTreeBuilder thead(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "thead", action);

        public static RenderTreeBuilder time(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "time", action);

        public static RenderTreeBuilder title(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "title", action);

        public static RenderTreeBuilder tr(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "tr", action);

        public static RenderTreeBuilder track(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "track", action);

        public static RenderTreeBuilder u(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "u", action);

        public static RenderTreeBuilder ul(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "ul", action);

        public static RenderTreeBuilder var(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "var", action);

        public static RenderTreeBuilder video(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "video", action);

        public static RenderTreeBuilder wbr(this RenderTreeBuilder b, Action<RenderTreeBuilder>? action = default) => ElementInline(b, "wbr", action);
    }
}

#nullable disable