// Copyright (c) The Egregore Project & Contributors. All rights reserved.
// 
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

using System.Runtime.InteropServices;
using System.Text;

namespace Blowdart.UI.Tests
{
	internal static class StringBuilderExtensions
	{
		public static void AppendAutoGeneratedHeader(this StringBuilder sb)
		{
			sb.AppendLine("//------------------------------------------------------------------------------");
			sb.AppendLine("// <auto-generated>");
			sb.AppendLine("//     This code was generated by a tool.");
			sb.AppendLine($"//     Runtime Version: {RuntimeInformation.FrameworkDescription}");
			sb.AppendLine("//");
			sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
			sb.AppendLine("//     the code is regenerated.");
			sb.AppendLine("// </auto-generated>");
			sb.AppendLine("//------------------------------------------------------------------------------");
			sb.AppendLine();
		}
	}
}